### ISSUE TITLE
Crash when i'm using andesite casing on create copycats and copycats+ blocks

### ISSUE THREAD

**Issue by furti-two** [copycats-plus/copycats#23]
video
https://github.com/copycats-plus/copycats/assets/68595920/8
[message.log](https://github.com/copycats-plus/copycats/files/14574299/message.log)
88c3a41-8a76-45a5-9e93-433f008f0cc7

**Comment by Bennyboy1695** [comment]
That link is invalid. We need a crash report if you are crashing.

**Comment by furti-two** [comment]
Negative index in crash report handler (21/26)
[15:24:54] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 6c24d096-99f5-4a75-a691-df8f1526f310
---- Minecraft Crash Report ----
// Shall we play a game?
Time: 3/12/24, 3:24 PM
Description: Tesselating block in world
java.lang.AbstractMethodError: Method com/simibubi/create/content/decoration/copycat/CopycatStepBlock.canConnectTexturesToward(Lnet/minecraft/world/level/BlockAndTintGetter;Lnet/minecraft/core/BlockPos;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;)Z is abstract
	at com.simibubi.create.content.decoration.copycat.CopycatStepBlock.canConnectTexturesToward(CopycatStepBlock.java) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:APP:copycats.mixins.json:copycat.step.CopycatStepBlockMixin,pl:mixin:A}
	at com.simibubi.create.foundation.block.connected.ConnectedTextureBehaviour.wrapOperation$zzn000$bypassIfShim(ConnectedTextureBehaviour.java:534) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:A}
	at com.simibubi.create.foundation.block.connected.ConnectedTextureBehaviour.testConnection(ConnectedTextureBehaviour.java:64) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:A}
	at com.simibubi.create.foundation.block.connected.ConnectedTextureBehaviour.buildContext(ConnectedTextureBehaviour.java:128) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:A}
	at com.simibubi.create.foundation.block.connected.CTModel.createCTData(CTModel.java:56) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.foundation.block.connected.CTModel.gatherModelData(CTModel.java:40) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.foundation.model.BakedModelWrapperWithData.getModelData(BakedModelWrapperWithData.java:24) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading}
	at com.simibubi.create.content.decoration.copycat.CopycatModel.gatherModelData(CopycatModel.java:57) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:APP:copycats.mixins.json:copycat.CopycatModelAccessor,pl:mixin:A}
	at com.simibubi.create.foundation.model.BakedModelWrapperWithData.getModelData(BakedModelWrapperWithData.java:24) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:51) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:67) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:runtimedistcleaner:A,re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:farmersdelight.mixins.json:HideBlockBreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_112865_(ChunkRenderDispatcher.java:640) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:instancemanage.ChunkRebuildHooksMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:557) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:instancemanage.ChunkRebuildHooksMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.m_194412_(ChunkRenderDispatcher.java:122) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at com.simibubi.create.content.decoration.copycat.CopycatStepBlock.canConnectTexturesToward(CopycatStepBlock.java) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:APP:copycats.mixins.json:copycat.step.CopycatStepBlockMixin,pl:mixin:A}
	at com.simibubi.create.foundation.block.connected.ConnectedTextureBehaviour.wrapOperation$zzn000$bypassIfShim(ConnectedTextureBehaviour.java:534) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:A}
	at com.simibubi.create.foundation.block.connected.ConnectedTextureBehaviour.testConnection(ConnectedTextureBehaviour.java:64) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:A}
	at com.simibubi.create.foundation.block.connected.ConnectedTextureBehaviour.buildContext(ConnectedTextureBehaviour.java:128) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:A}
	at com.simibubi.create.foundation.block.connected.CTModel.createCTData(CTModel.java:56) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.foundation.block.connected.CTModel.gatherModelData(CTModel.java:40) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.foundation.model.BakedModelWrapperWithData.getModelData(BakedModelWrapperWithData.java:24) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading}
	at com.simibubi.create.content.decoration.copycat.CopycatModel.gatherModelData(CopycatModel.java:57) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:APP:copycats.mixins.json:copycat.CopycatModelAccessor,pl:mixin:A}
	at com.simibubi.create.foundation.model.BakedModelWrapperWithData.getModelData(BakedModelWrapperWithData.java:24) ~[create-1.18.2-0.5.1.f.jar%2358!/:0.5.1.f] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:51) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:classloading,pl:runtimedistcleaner:A}
-- Block being tesselated --
Details:
	Block: Block{create:copycat_step}[facing=west,half=bottom,waterlogged=false]
	Block location: World: (12,56,8), Section: (at 12,8,8 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Stacktrace:
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBatched(BlockRenderDispatcher.java:67) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:runtimedistcleaner:A,re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:farmersdelight.mixins.json:HideBlockBreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_112865_(ChunkRenderDispatcher.java:640) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:instancemanage.ChunkRebuildHooksMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk$RebuildTask.m_5869_(ChunkRenderDispatcher.java:557) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:instancemanage.ChunkRebuildHooksMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.m_194412_(ChunkRenderDispatcher.java:122) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Pingui'/515, l='ClientLevel', x=12.90, y=56.00, z=6.32]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,56,0), Section: (at 0,8,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1403 game time, 1403 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:accessors.client.multiplayer.ClientLevelAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:client.world.MixinClientLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.block_tint.MixinClientLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.shipyard_entities.MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2264) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vs_clockwork-common.mixins.json:content.gravitron.MinecraftAccessor,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:valkyrienskies-common.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:create_interactive-common.mixins.json:client.MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.m_199948_(ChunkRenderDispatcher.java:129) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:655) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:vs_clockwork-common.mixins.json:content.gravitron.MinecraftAccessor,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:valkyrienskies-common.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:create_interactive-common.mixins.json:client.MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2376!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.4.jar%2352!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-1.5.8-prism.jar:1.5.8-prism] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?] {}
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, Clockwork: Gearwork
-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2667932680 bytes (2544 MiB) / 4250927104 bytes (4054 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Parsec Virtual Display Adapter
	Graphics card #0 vendor: Parsec Cloud, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=0.41.0.0
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9a60
	Graphics card #1 versionInfo: DriverVersion=30.0.101.2079
	Graphics card #2 name: NVIDIA GeForce RTX 3070 Laptop GPU
	Graphics card #2 vendor: NVIDIA (0x10de)
	Graphics card #2 VRAM (MB): 4095.00
	Graphics card #2 deviceId: 0x249d
	Graphics card #2 versionInfo: DriverVersion=31.0.15.5176
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 39423.66
	Virtual memory used (MB): 23415.36
	Swap memory total (MB): 23401.90
	Swap memory used (MB): 677.86
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 551.76, NVIDIA Corporation
	Window size: 1920x1057
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources, vs_clockwork:gearwork
	Current Language: English (US)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Pingui'/515, l='ServerLevel[New World]', x=12.90, y=56.00, z=6.32]]
	Data Packs: vanilla, mod:createbigcannons, mod:copycats, mod:ritchiesprojectilelib (incompatible), mod:mixinextras (incompatible), mod:create_confectionery, mod:littlecontraptions (incompatible), mod:vintageimprovements, mod:interiors (incompatible), mod:cloth_config (incompatible), mod:forge, mod:farmersdelight, mod:kotlinforforge, mod:curios (incompatible), mod:flywheel (incompatible), mod:create, mod:patchouli (incompatible), mod:ars_nouveau, mod:worldedit (incompatible), mod:ars_creo (incompatible), mod:littlelogistics (incompatible), mod:architectury (incompatible), mod:createtrackmap (incompatible), mod:valkyrienskies (incompatible), mod:vs_eureka (incompatible), mod:vs_clockwork (incompatible), mod:trackwork, mod:create_interactive (incompatible), mod:sliceanddice (incompatible)
	World Generation: Stable
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.12.0
		lowcodefml@null
	Mod List: 
		createbigcannons-forge-1.18.2-0.5.3.b.jar         |Create Big Cannons            |createbigcannons              |0.5.3.b-nightly-55e3|DONE      |Manifest: NOSIGNATURE
		copycats-1.1.0-mc1.18.2-all.jar                   |Create: Copycats+             |copycats                      |1.1.0-mc1.18.2      |DONE      |Manifest: NOSIGNATURE
		ritchiesprojectilelib-1.0.0-3a68f88+1.18.2-forge.j|Ritchie's Projectile Library  |ritchiesprojectilelib         |1.0.0-3a68f88+1.18.2|DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |DONE      |Manifest: NOSIGNATURE
		create-confectionery1.18.2_v1.0.9.jar             |Create Confectionery          |create_confectionery          |1.0.9               |DONE      |Manifest: NOSIGNATURE
		littlecontraptions-forge-1.18.2.2.jar             |Little Contraptions           |littlecontraptions            |1.18.2.2            |DONE      |Manifest: NOSIGNATURE
		vintageimprovements-1.18.2-0.1.2.0.jar            |Create: Vintage Improvements  |vintageimprovements           |1.18.2-0.1.2.0      |DONE      |Manifest: NOSIGNATURE
		interiors-0.5.2-mc1.18.2-FORGE.jar                |Create: Interiors             |interiors                     |0.5.2               |DONE      |Manifest: NOSIGNATURE
		cloth-config-forge-6.3.81.jar                     |Cloth Config v4 API           |cloth_config                  |6.3.81              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.4-universal.jar                 |Forge                         |forge                         |40.2.4              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.18.2-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.2.3        |DONE      |Manifest: NOSIGNATURE
		kffmod-3.12.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.12.0              |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.9.2.jar                   |Curios API                    |curios                        |1.18.2-5.0.9.2      |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.10-105.jar              |Flywheel                      |flywheel                      |0.6.10-105          |DONE      |Manifest: NOSIGNATURE
		create-1.18.2-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.18.2-2.9.0.jar                      |Ars Nouveau                   |ars_nouveau                   |2.9.0               |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.10.jar                          |WorldEdit                     |worldedit                     |7.2.10+1742f98      |DONE      |Manifest: NOSIGNATURE
		ars_creo-1.18.2-2.2.0.jar                         |Ars Creo                      |ars_creo                      |2.2.0               |DONE      |Manifest: NOSIGNATURE
		littlelogistics-mc1.18.2-v1.2.7.jar               |Little Logistics              |littlelogistics               |1.2.7               |DONE      |Manifest: NOSIGNATURE
		architectury-forge-4.11.93.jar                    |Architectury                  |architectury                  |4.11.93             |DONE      |Manifest: NOSIGNATURE
		create-track-map-1.4+mc1.18.2-forge-create-0.5.1.j|Create Track Map              |createtrackmap                |1.4                 |DONE      |Manifest: NOSIGNATURE
		valkyrienskies-118-2.1.1-beta.5.jar               |Valkyrien Skies 2             |valkyrienskies                |2.1.1-beta.5        |DONE      |Manifest: NOSIGNATURE
		eureka-1.4.0-beta.1.jar                           |VS Eureka Mod                 |vs_eureka                     |1.4.0-beta.1        |DONE      |Manifest: NOSIGNATURE
		clockwork-1.18.2-0.1.4-forge-df2c1c3e57.jar       |Clockwork: Create x Valkyrien |vs_clockwork                  |1.18.2-0.1.4-forge-d|DONE      |Manifest: NOSIGNATURE
		trackwork-1.18.2-0.0.1g-alpha.jar                 |Trackwork Mod                 |trackwork                     |1.18.2-0.0.1g-alpha |DONE      |Manifest: NOSIGNATURE
		create_interactive-118-forge-1.0.0-beta.3.jar     |Create: Interactive           |create_interactive            |1.0.0-beta.3        |DONE      |Manifest: NOSIGNATURE
		sliceanddice-forge-1.3.2.jar                      |Create Slice & Dice           |sliceanddice                  |1.3.2               |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 6c24d096-99f5-4a75-a691-df8f1526f310
	FML: 40.2
	Forge: net.minecraftforge:40.2.4
[15:24:54] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 388321c3-6ff0-4709-b5fc-19d62af3a072
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Pinpin\AppData\Roaming\PrismLauncher\instances\ADDON CREATE\.minecraft\crash-reports\crash-2024-03-12_15.24.54-client.txt
[15:24:54] [Server thread/INFO] [createtrackmap/]: Stopping Create Track Map server
[15:24:55] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[15:24:55] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[15:24:55] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Pingui lost connection: Server closed
Running deletePhysicsResources
[15:24:55] [Server thread/INFO] [minecraft/MinecraftServer]: Pingui left the game
[15:24:55] [Physics thread/INFO] [Burger Factory/]: Deleting VSPhysicsPipelineStage resources!
[15:24:55] [Physics thread/WARN] [or.va.co.im.sh.Ap/]: Physics pipeline ending
[15:24:55] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Stopping singleplayer server as player logged out
[15:24:55] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[15:24:55] [DefaultDispatcher-worker-7/INFO] [Burger Factory/]: VSPhysicsPipelineStage is fully deleted!
[15:24:55] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[15:24:55] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[15:24:55] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[15:24:55] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[15:24:55] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[15:24:55] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[15:24:55] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage: All dimensions are saved
AL lib: (EE) alc_cleanup: 1 device not closed
Le processus s'est arrêté avec le code de sortie -1.

**Comment by Bennyboy1695** [comment]
Known issue. Should be fixed soon

**Comment by VladisCrafter** [comment]
![image](https://github.com/copycats-plus/copycats/assets/122053125/4bf78e25-016e-49eb-9aca-9f03e7b00531)
# Huh?

**Comment by Bennyboy1695** [comment]
This should be fixed in the newer versions of the mod
