### ISSUE TITLE
[Bug]: [STDERR]: java.lang.NullPointerException [Fabric 1.20.1]

### ISSUE THREAD

**Issue by xR4YM0ND** [copycats-plus/copycats#41]
```js
java.lang.NullPointerException
at com.copycatsplus.copycats.multiloader.LogicalSidedProvider.get(LogicalSidedProvider.java:34)
at com.copycatsplus.copycats.config.FeatureToggle.lambda$refreshItemVisibility$5(FeatureToggle.java:89)
at com.copycatsplus.copycats.multiloader.Platform$Environment.runIfCurrent(Platform.java:40)
at com.copycatsplus.copycats.config.FeatureToggle.refreshItemVisibility(FeatureToggle.java:88)
at com.copycatsplus.copycats.config.CFeatures.onReload(CFeatures.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.simibubi.create.foundation.config.ConfigBase.onReload(ConfigBase.java:36)
at com.copycatsplus.copycats.config.SyncConfigBase.onReload(SyncConfigBase.java:69)
at com.copycatsplus.copycats.config.fabric.CCConfigsImpl.onReload(CCConfigsImpl.java:28)
at fuzs.forgeconfigapiport.api.config.v2.ModConfigEvents$ModConfigEventsHolder.lambda$create$2(ModConfigEvents.java:133)
at fuzs.forgeconfigapiport.impl.core.FabricAbstractions.fireConfigReloading(FabricAbstractions.java:20)
at net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigWatcher.run(ConfigFileTypeHandler.java:160)
at com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)
```

[latest.log](https://gist.github.com/xR4YM0ND/f08fff74d43bf8cc317bd8aac2a0bf4c#file-latest-log-L571)

**Comment by Bennyboy1695** [comment]
Could really do with more info than just the log like is this a crash, does it break anything?

**Comment by xR4YM0ND** [comment]
Idk if this breaks something, but it appears in the log, that's why i let you know.
It only appears 5/10 times & when Copycats+ gets loaded with these mods:

Fabric 1.20.1
Loader 0.15.9

- Architectury 9.2.14
- Create 0.5.1-f build 1335
- Create: Copycats+ 1.2.6
- Fabric API 0.92.0
- Forge Config API Port 8.0.0
- ModernFix 5.15.0

[latest.log](https://gist.github.com/xR4YM0ND/b598512d1d9ec9f3b80d52f7426e7ab1) with only these mods

**Comment by Bennyboy1695** [comment]
I do believe that this issue is the config mod (forge config api port) is sending a config event on game start which is making that error show because its looking for an instance of the server. We can probably find a way to hide that error but it shouldnt affect anything anyway so will be a low priority

**Comment by xR4YM0ND** [comment]
Alrighty, thank you for your time!

**Comment by hlysine** [comment]
This seems to be inconsistent, and the error has also changed in newer versions. Closing since it doesn't affect anything.
