### ISSUE TITLE
Crashes on Servers

### ISSUE THREAD

**Issue by AzrouStone** [copycats-plus/copycats#7]
I use Indium/Sodium for my server to run more smoothly and when someone uses one of these copycat blocks, that chunk corrupts and kicks any player near the area.

java.util.concurrent.CompletionException: net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.findNext(WorkStealingFutureDrain.java:47)
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.hasNext(WorkStealingFutureDrain.java:28)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:123)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:59)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:334)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:312)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:197)
	at net.minecraft.class_761.method_3273(class_761.java:21554)
	at net.minecraft.class_761.method_22710(class_761.java:1240)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:61)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$eai000$indium$onRenderBlock(ChunkRenderRebuildTask.java:1054)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:99)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:285)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.stealTask(ChunkBuilder.java:245)
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.findNext(WorkStealingFutureDrain.java:54)
	... 17 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1058.method_4577()" because "sprite" is null
	at com.simibubi.create.foundation.block.render.SpriteShiftEntry.getUnInterpolatedU(SpriteShiftEntry.java:42)
	at com.simibubi.create.foundation.model.BakedModelHelper.cropAndMove(BakedModelHelper.java:49)
	at com.copycatsplus.copycats.content.copycat.ISimpleCopycatModel.assembleQuad(ISimpleCopycatModel.java:69)
	at com.copycatsplus.copycats.content.copycat.ISimpleCopycatModel.assembleQuad(ISimpleCopycatModel.java:59)
	at com.copycatsplus.copycats.content.copycat.ISimpleCopycatModel.assemblePiece(ISimpleCopycatModel.java:35)
	at com.copycatsplus.copycats.content.copycat.layer.CopycatLayerModel.emitCopycatQuads(CopycatLayerModel.java:30)
	at com.copycatsplus.copycats.content.copycat.SimpleCopycatModel.lambda$emitBlockQuadsInner$0(SimpleCopycatModel.java:41)
	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:42)
	at link.infra.indium.renderer.render.BaseFallbackConsumer.renderQuad(BaseFallbackConsumer.java:102)
	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:92)
	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:57)
	at net.fabricmc.fabric.api.renderer.v1.render.RenderContext$1.accept(RenderContext.java:62)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at com.copycatsplus.copycats.content.copycat.SimpleCopycatModel.emitBlockQuadsInner(SimpleCopycatModel.java:44)
	at com.simibubi.create.content.decoration.copycat.CopycatModel.emitBlockQuads(CopycatModel.java:73)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:56)
	... 22 more

**Comment by lenamerkli** [comment]
Please upload the entire crashlog. Here's the tutorial to find it: https://minecraft.wiki/w/Tutorials/Obtaining_a_crash_report
